name: CI Build & Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.24.2
      - name: Build
        run: go build -v ./...
      - name: fmt
        run: gofmt -s -l -e .
