name: CI Build & Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: 1.24.2
      - name: Build
        run: go build -v ./...
      - name: fmt
        run: gofmt -s -l -e .
